title: Articles
description: A collection of my code explorations
theme: just-the-docs
color_scheme: dark


defaults:
  - scope:
      path: "docs/notebooks" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

url: https://theevildoof.github.io
baseurl: /articles  # Important: this is the repo name

aux_links:
  Template Repository: https://github.com/theevildoof/articles
